name: Gradle Build
on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: "17"

      cache-read-only:
        required: false
        type: boolean
        default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}

      build-version:
        required: false
        type: string

      build-args:
        required: false
        type: string
        default: build

      upload-artifacts:
        required: false
        type: boolean
        default: true

      artifact-name:
        required: false
        type: string
        default: build-artifacts

      artifacts-path:
        required: false
        type: string
        default: build/libs/*.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: zulu

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          cache-read-only: ${{ inputs.cache-read-only }}
          gradle-home-cache-cleanup: true
          gradle-home-cache-includes: |
            caches
            notifications
            jdks

          gradle-home-cache-excludes: |
            caches/build-cache-1
            caches/keyrings

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Calculate build version
        id: build-version
        run: |
          VERSION=${{ inputs.build-version }}
          if [ -z "$VERSION" ]; then
            VERSION=${{ github.sha }}
            VERSION=${VERSION:0:7}
          elif [[ $VERSION == v* ]]; then
            VERSION=${VERSION:1}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew ${{ inputs.build-args }}
        env:
          BUILD_VERSION: ${{ steps.build-version.outputs.version }}

      - name: Upload build artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifacts-path }}
